### ISSUE TITLE
Persistence of Subscriptions

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-msg-node-nomatrix#1]
The Subscription Manager should persist listeners added to BUS in order not to loose them in case it is for some reason rebooted. When rebooted, the Subscription Manager should look on persisted subscriptions and add them again as listeners into the BUS.

**Comment by sdruesedow** [comment]
Started ... I'm just evaluating https://github.com/simonlast/node-persist which seems to be suitable. It supports asynchronous as well as synchronous operation.

**Comment by sdruesedow** [comment]
Done - version with subscription persistence is now active on rethink.tlabscloud.com and rethink-dev.tlabscloud.com.
