### ISSUE TITLE
Update protostub with state machine 

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-msg-node-nomatrix#7]
As specified [here](https://github.com/reTHINK-project/specs/blob/master/messaging-framework/stub-specification.md#state-machine)

Tests can be performed with "dev-protostub-state-machine" branch of the runtime-core branch.

Vertx protostub was already updated with this state machine implementation also in a "dev-protostub-state-machine" branch.

**Comment by sdruesedow** [comment]
implemented in new branch dev-protostub-state-machine"

**Comment by sdruesedow** [comment]
tested successfully with development environment, in production environment the stub loading process got stuck after "created"
