### ISSUE TITLE
Via Header for outgoing messages

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-msg-node-nomatrix#8]
To avoid loops when reporter and observers are hosted in the same runtime instance, add the "via" header  to outgoing messages ie messages delivered to message node, and filter incoming messages when the via header contains the protostub URL.

**Comment by sdruesedow** [comment]
The via header handling is included in the stub since more than a year. Is this a new requirement? Did something change?

**Comment by sdruesedow** [comment]
as discussed, it was there only for incoming messages (from MN). Now it is also required for incoming messages.

**Comment by sdruesedow** [comment]
pushed changes to "dev-protostub-state-machine" branch, tested with toolkit in development mode
